server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stats-server.url=http://localhost:9090